---
# tasks file for php
- name: "Install PHP on Debian"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - php8.1
      - php8.1-fpm
      - php8.1-cli
      - php8.1-common
      - php8.1-curl
      - php8.1-mbstring
      - php8.1-mysql
      - php8.1-xml
      - php8.1-gd
      - php8.1-exif
    state: latest
  when: (ansible_facts['os_family'] == "Debian")
  