---
# tasks file for mysql
- name: Install MariaDB Server on Debian
  apt:
    update_cache: yes
    name:
      - mariadb-server
      - python3-pymysql
    state: present
  when: (ansible_facts['os_family'] == "Debian")

- name: "Start MariaDB"
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create database on MariaDB - Debian
  mysql_db:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ db_wp_name }}"
    state: present
  when: (ansible_facts['os_family'] == "Debian")

- name: Create user with password, all privileges in database
  mysql_user:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ db_wp_username }}"
    password: "{{ db_wp_password }}"
    priv: "{{ db_wp_name }}.*:ALL,GRANT"
    state:  present
  when: (ansible_facts['os_family'] == "Debian")